repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0  # Use the ref you want to point at
    hooks:
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: check-xml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.4.2
  hooks:
    - id: forbid-tabs
    - id: remove-tabs
